name: Backend CI/CD

on:
  push:
    branches:
      - feature/full-stack
      - main
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/MuchToDo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ secrets.ECR_REPOSITORY }}:latest \
            .

      #################################################
      # DEPLOY TO EC2 SERVER 1
      #################################################

      - name: Deploy to EC2 Server 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/starttech-backend
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend --restart always -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest
          #script: |
           #aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            #docker pull ${{ secrets.ECR_REPOSITORY }}:latest

            #docker stop backend || true
            #docker rm backend || true

            #docker run -d --name backend --restart always -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest

      #################################################
      # DEPLOY TO EC2 SERVER 2
      #################################################

      - name: Deploy to EC2 Server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            docker pull ${{ secrets.ECR_REPOSITORY }}:latest

            docker stop backend || true
            docker rm backend || true

            docker run -d --name backend --restart always -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest